// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oovinovegyumzfwhmyem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vdmlub3ZlZ3l1bXpmd2hteWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTI2MDgsImV4cCI6MjA3MTM2ODYwOH0.vk1uwd2YWCeGs7v-zVnBba8gF0eYNVOj3wWh-AlBb5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});